baseurl = "/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

[params]
  contentTypeName = "post"
  defaultTheme = "light"
  showMenuItems = 2
  showReadingTime = false

[languages]
  [languages.en]
    title = "Toon Sevrin's tech blog"
    subtitle = "A blog by Toon Sevrin"
    keywords = "technology, kubernetes, programming, devops, gitops"
    copyright = "Copyright Toon Sevrin, © 2020"
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "Toon Sevrin"
      logoHomeLink = "/"

    [languages.en.menu]
